# Generated by Django 6.0.6 on 2026-06-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attendance_record',
            new_name='AttendanceRecord',
        ),
        migrations.RenameModel(
            old_name='qr_session',
            new_name='QrSession',
        ),
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_attendance_per_session',
        ),
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='qr_session_id',
            new_name='qr_session',
        ),
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='remember_me_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'qr_session'), name='unique_attendance_per_session'),
        ),
    ]
