# Generated by Django 6.0.6 on 2026-06-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_attendance_record_attendancerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrsession',
            name='class_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
